import './style/tailwind.css';
export * from './components/TestComp';
export * from './components/EntityComponents';
export * from './components/HeroComponents';
export * from './components/DimComponents';
export * from './components/KeyfeaturesComponents';
export * from './components/BrandComponents';
export * from './components/EnergyComponents';
export * from './components/CollageComponents';
export * from './components/BrandPolicy/Policy';
export * from './components/Common';